services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: mhmh
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
