-- situation table
CREATE TABLE situation
(
    type       VARCHAR(100) NOT NULL,
    title      VARCHAR(100),
    color      VARCHAR(12), -- 5881F3
    text_color VARCHAR(12), -- FFFFFF
    CONSTRAINT pk_situation PRIMARY KEY (type)
);

-- topic table
CREATE TABLE topic
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content        VARCHAR(500)                             NOT NULL,
    situation_type VARCHAR(100),
    CONSTRAINT pk_topic PRIMARY KEY (id)
);

ALTER TABLE topic
    ADD CONSTRAINT FK_TOPIC_ON_SITUATION_TYPE FOREIGN KEY (situation_type) REFERENCES situation (type);

-- topic tip table
CREATE TABLE topic_tip
(
    id    INTEGER NOT NULL,
    title VARCHAR(100),
    CONSTRAINT pk_topic_tip PRIMARY KEY (id)
);

CREATE TABLE topic_tip_contents
(
    topic_tip_id INTEGER NOT NULL,
    contents     VARCHAR(500)
);

ALTER TABLE topic_tip_contents
    ADD CONSTRAINT fk_topic_tip_contents_on_topic_tip_entity FOREIGN KEY (topic_tip_id) REFERENCES topic_tip (id);

