-- situation table
CREATE TABLE situation
(
    type       VARCHAR(100) NOT NULL,
    title      VARCHAR(100),
    color      VARCHAR(12), -- 5881F3
    text_color VARCHAR(12), -- FFFFFF
    CONSTRAINT pk_situation PRIMARY KEY (type)
);

CREATE TABLE person_situation
(
    type       VARCHAR(100) NOT NULL,
    title      VARCHAR(100),
    color      VARCHAR(12), -- 5881F3
    text_color VARCHAR(12), -- FFFFFF
    CONSTRAINT pk_person_situation PRIMARY KEY (type)
);

-- topic table
CREATE TABLE topic
(
    topic_id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content        VARCHAR(500)                             NOT NULL,
    situation_type VARCHAR(500),
    CONSTRAINT pk_topic PRIMARY KEY (topic_id)
);

-- topic tip table
CREATE TABLE topic_tip
(
    topic_tip_id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(200),
    topic_id     INTEGER,
    CONSTRAINT pk_topic_tip PRIMARY KEY (topic_tip_id)
);

CREATE TABLE topic_tip_contents
(
    c_topic_tip_id INTEGER NOT NULL,
    contents               VARCHAR(500)
);

ALTER TABLE topic_tip
    ADD CONSTRAINT FK_TOPIC_TIP_ON_TOPIC FOREIGN KEY (topic_id) REFERENCES topic (topic_id);

ALTER TABLE topic_tip_contents
    ADD CONSTRAINT fk_topic_tip_contents_on_topic_tip_entity FOREIGN KEY (c_topic_tip_id) REFERENCES topic_tip (topic_tip_id);