-- situation insert
INSERT INTO situation values ('DATE', '소개팅', '5881F3', 'FFFFFF');
INSERT INTO situation values ('COMPANY', '회사', '5881F3', 'FFFFFF');
INSERT INTO situation values ('COFFEE', '커피챗', '5881F3', 'FFFFFF');
INSERT INTO situation values ('SMALL', '스몰토크', '5881F3', 'FFFFFF');
INSERT INTO situation values ('TOGETHER', '단체 모임', '5881F3', 'FFFFFF');
INSERT INTO situation values ('COUPLE', '커플', '5881F3', 'FFFFFF');

INSERT INTO person_situation values ('COLLEAGUE', '직장 동료', '5881F3', 'FFFFFF');
INSERT INTO person_situation values ('SENIORITY', '선후배', '5881F3', 'FFFFFF');
INSERT INTO person_situation values ('CLUB', '동호회', '5881F3', 'FFFFFF');
INSERT INTO person_situation values ('OLD_FRIEND', '오랜만에 만난 친구', '5881F3', 'FFFFFF');
INSERT INTO person_situation values ('FAMILY', '가족', '5881F3', 'FFFFFF');
INSERT INTO person_situation values ('FIRST_FRIEND', '처음 만난 사람', '5881F3', 'FFFFFF');

-- INSERT INTO topic_tip (topic_tip_id, title, topic_id) VALUES (1, '소제목 1입니다.', 1);
-- INSERT INTO topic_tip_contents (c_topic_tip_id, contents)
-- VALUES (1, 'Tip Content 1'),
--        (1, 'Tip Content 2');
-- INSERT INTO topic_tip (topic_tip_id, title, topic_id) VALUES (2, '소제목 2입니다.', 1);
-- INSERT INTO topic_tip_contents (c_topic_tip_id, contents)
-- VALUES (2, 'Tip Content 1'),
--        (2, 'Tip Content 2');

-- topic insert

TRUNCATE TABLE topic_tip RESTART IDENTITY CASCADE;

DELETE FROM topic; -- 임시 데이터 삭제
ROLLBACK; -- 트랜잭션 롤백

-- START TRANSACTION;
-- 스몰토크 토픽
START TRANSACTION;
INSERT INTO topic VALUES (1, '최근에 본 가장 웃긴 밈이 뭔가요?', 'SMALL');
INSERT INTO topic VALUES (2, '즐겨보는 드라마나 영화가 있나요?', 'SMALL');
INSERT INTO topic VALUES (3, '나만의 스트레스 해소법이 있다면?', 'SMALL');
INSERT INTO topic VALUES (4, '여행 가고싶은 나라가 있나요?', 'SMALL');
INSERT INTO topic VALUES (5, '요즘 즐기는 취미가 있나요?', 'SMALL');
INSERT INTO topic VALUES (6, '좋아하는 계절이 있나요?', 'SMALL');
INSERT INTO topic VALUES (7, '날씨가 ~하네요. 좋아하는 계절에 있나요?', 'SMALL');
INSERT INTO topic VALUES (8, '로또가 당첨되면 뭐할거에요?', 'SMALL');
INSERT INTO topic VALUES (9, '주말에 뭐하세요?', 'SMALL');
INSERT INTO topic VALUES (10, 'MBTI가 어떻게 되세요?', 'SMALL');
INSERT INTO topic VALUES (11, '좋아하는 연예인이 있나요?', 'SMALL');
INSERT INTO topic VALUES (12, '최근에 가장 만족스러웠던 소비는 무엇인가요?', 'SMALL');
INSERT INTO topic VALUES (13, '좋아하는 음식은 무엇인가요?', 'SMALL');
INSERT INTO topic VALUES (14, '선호하는 패션 스타일이 있나요?', 'SMALL');
INSERT INTO topic VALUES (15, '건강 관리 방법이 있나요?', 'SMALL');
INSERT INTO topic VALUES (16, '잠은 잘 주무시나요?', 'SMALL');
INSERT INTO topic VALUES (17, '만약에 내 눈앞에 모든 음식이 똥으로 보인다면?', 'SMALL');
INSERT INTO topic VALUES (18, '아침형 인간이세요?', 'SMALL');
INSERT INTO topic VALUES (19, '여행지 추천해주실 수 있나요?', 'SMALL');
INSERT INTO topic VALUES (20, '최근에 가장 뿌듯했던 순간이 있으세요?', 'SMALL');
INSERT INTO topic VALUES (21, '최근에 새로 배운게 있나요?', 'SMALL');

-- 단체 모임
INSERT INTO topic VALUES (22, '이 모임에 처음 온 사람이 있나요?', 'TOGETHER');
INSERT INTO topic VALUES (23, '처음 모인 순간을 기억하나요?', 'TOGETHER');
INSERT INTO topic VALUES (24, '단체로 여행 간다면 어디로 가고싶은가요?', 'TOGETHER');
INSERT INTO topic VALUES (25, '요즘 모임에 추가되었으면 하는 활동이 있나요?', 'TOGETHER');
INSERT INTO topic VALUES (26, '다음 모임 장소는 어디면 좋을까요?', 'TOGETHER');
INSERT INTO topic VALUES (27, '모임 이름으로 n행시를 지어주세요!', 'TOGETHER');
INSERT INTO topic VALUES (28, '모임에 공유하고 싶은 팁이 있다면?', 'TOGETHER');
INSERT INTO topic VALUES (29, '모임에 참여하게 된 계기가 뭔가요?', 'TOGETHER');
INSERT INTO topic VALUES (30, '보통 뭐 하면서 시간을 보내시나요?', 'TOGETHER');
INSERT INTO topic VALUES (31, '다른 취미 있으신가요?', 'TOGETHER');
INSERT INTO topic VALUES (32, '제일 만족스러웠던 활동이 뭔가요?', 'TOGETHER');
INSERT INTO topic VALUES (33, '이전에 다른 모임 참여해 보신적 있나요?', 'TOGETHER');
INSERT INTO topic VALUES (34, '우리 모임에 개선되었으면 하는 점 있나요?', 'TOGETHER');
INSERT INTO topic VALUES (35, '상상했던 것과 우리 모임이 비슷한가요?', 'TOGETHER');
INSERT INTO topic VALUES (36, '상상했던 것과 우리 모임이 다른 점이 있나요?', 'TOGETHER');
INSERT INTO topic VALUES (37, '우리 모임에 호감가는 사람이 있나요?', 'TOGETHER');
INSERT INTO topic VALUES (38, '우리 모임을 추천해주고 싶은 사람이 있나요?', 'TOGETHER');
INSERT INTO topic VALUES (39, '첫 인상이 어땠나요?', 'TOGETHER');
INSERT INTO topic VALUES (40, '첫인상과 다른 사람이 있나요?', 'TOGETHER');

-- 회사 토픽
INSERT INTO topic VALUES (41, '회사 주변 맛집 아세요?', 'COMPANY');
INSERT INTO topic VALUES (42, '출퇴근 시간 얼마나 걸리세요?', 'COMPANY');
INSERT INTO topic VALUES (43, '요즘 즐겨보는 유투버 있어요?', 'COMPANY');
INSERT INTO topic VALUES (44, '휴가 계획 있어요?', 'COMPANY');
INSERT INTO topic VALUES (45, '요즘에 즐기는 취미 있어요?', 'COMPANY');
INSERT INTO topic VALUES (46, '쉬는날엔 뭐하세요?', 'COMPANY');
INSERT INTO topic VALUES (47, '업무의 효율을 어떻게 끌어올리나요?', 'COMPANY');
INSERT INTO topic VALUES (48, '출퇴근 시간에 뭐 하세요?', 'COMPANY');
INSERT INTO topic VALUES (49, '회사에 나만 아는 스팟이 있나요?', 'COMPANY');
INSERT INTO topic VALUES (50, '점심 메뉴 고르는 꿀팁 있나요?', 'COMPANY');
INSERT INTO topic VALUES (51, '스트레스 해소법이 어떻게 되나요?', 'COMPANY');
INSERT INTO topic VALUES (52, '보통 퇴근하면 뭐 하시나요?', 'COMPANY');
INSERT INTO topic VALUES (53, '재택 근무와 출근 중 어떤 걸 선호하시나요?', 'COMPANY');
INSERT INTO topic VALUES (54, '요즘 일이 힘들진 않으신가요?', 'COMPANY');
INSERT INTO topic VALUES (55, '점심시간에 뭐 하시나요?', 'COMPANY');
INSERT INTO topic VALUES (56, '회사에 있었으면 하는 복지가 있나요?', 'COMPANY');
INSERT INTO topic VALUES (57, '보통 몇시쯤 일어나세요?', 'COMPANY');
INSERT INTO topic VALUES (58, '주말 잘 보내셨어요?', 'COMPANY');
INSERT INTO topic VALUES (59, '업무할때 노래 들으세요?', 'COMPANY');
INSERT INTO topic VALUES (60, '사무실 꿀템 추천해주세요!', 'COMPANY');

-- 커피챗 토픽
INSERT INTO topic VALUES (61, '요즘 주로 사용하는 앱이나 툴은 뭔가요?', 'COFFEE');
INSERT INTO topic VALUES (62, '평소에 인사이트는 어디서 얻으세요?', 'COFFEE');
INSERT INTO topic VALUES (63, '지금까지의 커피쳇 경험 중 가장 기억에 남은 순간이 있나요?', 'COFFEE');
INSERT INTO topic VALUES (64, '업무 중,요가장 긴장했던 순간이 있다면?', 'COFFEE');
INSERT INTO topic VALUES (65, '가장 해주고싶은 조언이 있을까요?', 'COFFEE');
INSERT INTO topic VALUES (66, '업무와 휴식을 어떻게 분리하나요?', 'COFFEE');
INSERT INTO topic VALUES (67, '가장 좋았던 워크숍 경험이 있다면?', 'COFFEE');
INSERT INTO topic VALUES (68, '최근 업계 트랜드는 어떻게 변하고 있나요?', 'COFFEE');
INSERT INTO topic VALUES (69, '요즘 관심있는 기술이 있다면?', 'COFFEE');
INSERT INTO topic VALUES (70, '추천하고 싶은 강의가 있다면?', 'COFFEE');
INSERT INTO topic VALUES (71, '최근에 가입한 유익한 커뮤니티가 있나요?', 'COFFEE');
INSERT INTO topic VALUES (72, '커뮤니케이션 팁이 있을까요?', 'COFFEE');
INSERT INTO topic VALUES (73, '다음 커리어 목표는 어떻게 되세요?', 'COFFEE');
INSERT INTO topic VALUES (74, '이 업계를 선택한 이유가 있나요?', 'COFFEE');
INSERT INTO topic VALUES (75, '스트레스 해소법이 있을까요?', 'COFFEE');
INSERT INTO topic VALUES (76, '번아웃이 온 적 있으세요?', 'COFFEE');
INSERT INTO topic VALUES (77, '이직 팁 있으세요?', 'COFFEE');
INSERT INTO topic VALUES (78, '회사 분위기는 어떤가요?', 'COFFEE');
INSERT INTO topic VALUES (79, '책 읽는 거 좋아하세요?', 'COFFEE');
INSERT INTO topic VALUES (80, '현재 직무에서 주로 어떤 일을 하시나요?', 'COFFEE');
INSERT INTO topic VALUES (81, '현재 직무를 선택하게 된 특별한 계기가 있으신가요?', 'COFFEE');

-- 소개팅 토픽
INSERT INTO topic VALUES (82, '휴가를 간다면 어디로 가고 싶으세요?', 'DATE');
INSERT INTO topic VALUES (83, '이상형이 어떻게 되세요?', 'DATE');
INSERT INTO topic VALUES (84, '취미가 어떻게 되세요?', 'DATE');
INSERT INTO topic VALUES (85, '좋아하는 동물 있으세요?', 'DATE');
INSERT INTO topic VALUES (86, '하시는 운동 있으세요?', 'DATE');
INSERT INTO topic VALUES (87, '가장 좋아하는 음식이 뭐예요?', 'DATE');
INSERT INTO topic VALUES (88, '자기 전엔 주로 무엇을 하시나요?', 'DATE');
INSERT INTO topic VALUES (89, 'MBTI가 어떻게 되세요?', 'DATE');
INSERT INTO topic VALUES (90, '어제 뭐 하셨어요?', 'DATE');
INSERT INTO topic VALUES (91, '어릴때 꿈이 무엇이었나요?', 'DATE');
INSERT INTO topic VALUES (92, '연애할 때 가장 중요하게 생각하는게 뭔가요?', 'DATE');
INSERT INTO topic VALUES (93, '어떻게 소개받게된 거에요?', 'DATE');
INSERT INTO topic VALUES (94, '첫만남에서 꼭 알고 싶은게 있으신가요?', 'DATE');
INSERT INTO topic VALUES (95, '일 하신지는 얼마나 되셨어요?', 'DATE');
INSERT INTO topic VALUES (96, '못 드시는 음식이 있으세요?', 'DATE');
INSERT INTO topic VALUES (97, '어떤 노래 좋아하세요?', 'DATE');
INSERT INTO topic VALUES (98, '쉴땐 주로 무엇을 하시나요?', 'DATE');
INSERT INTO topic VALUES (99, '요즘 행복하다고 느끼는 순간이 있나요?', 'DATE');
INSERT INTO topic VALUES (100, '커피 좋아하세요?', 'DATE');
INSERT INTO topic VALUES (101, '오시는 길은 괜찮으셨어요?', 'DATE');
INSERT INTO topic VALUES (102, '새로 배워보고 싶은거 있으세요?', 'DATE');
INSERT INTO topic VALUES (103, '보통 몇시에 출근하고 퇴근하세요?', 'DATE');
INSERT INTO topic VALUES (104, '올해 꼭 이루고 싶은게 있으세요?', 'DATE');
INSERT INTO topic VALUES (105, '자주 보시는 유튜브 채널 있으세요?', 'DATE');
INSERT INTO topic VALUES (106, '책 읽는 거 좋아하세요?', 'DATE');

-- 커플
INSERT INTO topic VALUES (107, '가장 좋았던 여행지를 말해볼까요?', 'COUPLE');
INSERT INTO topic VALUES (108, '서운했던 일을 말해보세요!', 'COUPLE');
INSERT INTO topic VALUES (109, '서로의 좋은 점을 하나씩 말해볼까요?', 'COUPLE');
INSERT INTO topic VALUES (110, '서로의 외모 중 가장 마음에 드는 곳이 어디인가요?', 'COUPLE');
INSERT INTO topic VALUES (111, '결혼은 몇살에 하고 싶은가요?', 'COUPLE');
INSERT INTO topic VALUES (112, '서로의 첫인상에 대해 말해보아요!', 'COUPLE');
INSERT INTO topic VALUES (113, '같이 보고싶은 영화가 있나요?', 'COUPLE');
INSERT INTO topic VALUES (114, '기념일에 해보고싶은 활동이 있나요?', 'COUPLE');
INSERT INTO topic VALUES (115, '서로 닮은 동물 찾아볼까요?', 'COUPLE');
INSERT INTO topic VALUES (116, '최근에 고마웠던 순간이 있을까요?', 'COUPLE');
INSERT INTO topic VALUES (117, '기억나는 첫만남을 말해보세요!', 'COUPLE');
INSERT INTO topic VALUES (118, '버킷리스트를 공유해볼까요?', 'COUPLE');
INSERT INTO topic VALUES (119, '여행가고 싶은 곳을 서로 알려주세요!', 'COUPLE');
INSERT INTO topic VALUES (120, '결혼 한다면 자녀 계획을 상상해볼까요?', 'COUPLE');
INSERT INTO topic VALUES (121, '데이트 통장에 대해 어떻게 생각하세요?', 'COUPLE');
INSERT INTO topic VALUES (122, '만약에 사랑하는 사람이 내 눈앞에서 돌맹이로 변한다면?', 'COUPLE');
INSERT INTO topic VALUES (123, '내가 바퀴벌레로 변한다면?', 'COUPLE');
INSERT INTO topic VALUES (124, '상대방에게 가족을 소개시켜 주고 싶나요?', 'COUPLE');
INSERT INTO topic VALUES (125, '상대방이 바람을 피운다면?', 'COUPLE');
INSERT INTO topic VALUES (126, '상대방이 나랑 헤어지고 내 친한친구랑 사귄다면?', 'COUPLE');

END;

-- 직장 동료 토픽
START TRANSACTION;

INSERT INTO topic VALUES (127, '회사 주변 맛집 추천 해주기', 'COLLEAGUE');
INSERT INTO topic VALUES (128, '출퇴근 시간에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (129, '취미에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (130, '휴가 계획 공유 해주기', 'COLLEAGUE');
INSERT INTO topic VALUES (131, '좋아하는 운동에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (132, '쉬는 날 하는 일에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (133, '업무할 때 듣는 노래 공유해주기', 'COLLEAGUE');
INSERT INTO topic VALUES (134, '스트레스 해소하는 방법에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (135, '요즘 업무 만족도에 대해 공유해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (136, '퇴근 후 일상 공유해주기', 'COLLEAGUE');
INSERT INTO topic VALUES (137, '재택근무에 대한 생각 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (138, '회사 복지에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (139, '업무할 때 듣는 노래 공유 해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (140, '최근 본 드라마와 영화 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (141, '사무실 애착템 소개 해주기', 'COLLEAGUE');
INSERT INTO topic VALUES (142, '좋아하는 가수 이야기 해주기', 'COLLEAGUE');
INSERT INTO topic VALUES (143, '회사에서 먹은 음식 중 가장 맛있었던 것 말해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (144, '새롭게 배우고 싶은 것 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (145, '일하면서 보람된 순간에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (146, '주말에 주로 뭘 먹는지 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (147, '평소 루틴에 대해 이야기해보기', 'COLLEAGUE');
INSERT INTO topic VALUES (148, '학교/회사 생활 중 힘든 일은 없는지 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (149, '학교/회사 생활 중 가장 즐거웠던 일은 무엇인지 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (150, '학교/회사 생활 중 가장 뿌듯헀던 경험을 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (151, '학교/회사 생활 중 가장 아쉬웠던 경험을 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (152, '요즘 학교/회사에서 느끼는 감정을 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (153, '10년 뒤에 무엇을 하고 싶은지 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (154, '학교/회사에서 갖고 있는 본인만의 원칙에 대해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (155, '자신만의 학교/회사 생활 팁을 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (156, '일과 시간이 끝난 후 자신이 하는 일을 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (157, '등교/출근을 하지 않을 때는 무엇을 하며 보내는지 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (158, '하고 있는 자기 계발에 대해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (159, '서로의 장점에 대해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (160, '서로에게 응원해주기', 'SENIORITY');
INSERT INTO topic VALUES (161, '가장 힘든 점에 대해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (162, '성장하는 방법에 대해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (163, '우리 조직(과/팀)의 특징에 대해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (164, '조직에서 높은 퍼포먼스를 내는 사람들의 공통점 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (165, '가장 많이 하는 실수에 대해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (166, '최근에 읽은 책에 관해 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (167, '가장 존경하는 사람을 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (168, '어릴 때와 지금의 가치관 차이 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (169, '5년 후의 목표를 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (170, '앞으로 해보고 싶은 일 얘기해보기', 'SENIORITY');
INSERT INTO topic VALUES (171, 'A를 처음 시작하게 된 계기에 대해 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (172, 'A를 하면서 가장 재미있었던 순간은 언제였는지 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (173, 'A와 관련해서 최근에 새롭게 배운 것이 있는지 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (174, 'A를 하면서 가장 어려웠던 점에 대해 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (175, 'A를 할 때 꼭 필요한 장비나 도구에 대해 추천해보기', 'CLUB');
INSERT INTO topic VALUES (176, 'A와 관련된 추천 도서나 영상이 있는지 공유해보기', 'CLUB');
INSERT INTO topic VALUES (177, 'A를 하면서 경험한 가장 짜릿한 순간에 대해 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (178, 'A를 배우고 싶어하는 사람에게 해주고 싶은 조언을 나눠보기', 'CLUB');
INSERT INTO topic VALUES (179, 'A와 비슷한 다른 취미나 활동을 해본 적이 있는지 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (180, 'A를 하면서 생긴 가장 큰 변화에 대해 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (181, 'A를 하면서 스트레스를 받을 때 어떻게 해결하는지 공유해보기', 'CLUB');
INSERT INTO topic VALUES (182, 'A를 하면서 생긴 가장 소중한 추억을 공유해보기', 'CLUB');
INSERT INTO topic VALUES (183, 'A를 하면서 만난 특별한 사람들에 대해 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (184, 'A를 하면서 겪었던 예상치 못한 경험을 나눠보기', 'CLUB');
INSERT INTO topic VALUES (185, 'A를 통해 성취감을 느꼈던 순간에 대해 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (186, 'A와 관련된 행사나 축제에 가본 적이 있는지 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (187, 'A와 관련된 독특한 경험을 해본 적이 있는지 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (188, 'A를 처음 시작할 때 나에게 도움이 되었던 팁을 공유해보기', 'CLUB');
INSERT INTO topic VALUES (189, 'A를 하면서 감동받았던 순간이나 이야기를 나눠보기', 'CLUB');
INSERT INTO topic VALUES (190, 'A와 관련해서 꼭 한번 도전해보고 싶은 목표가 있는지 얘기해보기', 'CLUB');
INSERT INTO topic VALUES (191, '그 동안 어떻게 지냈는지 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (192, '최근에 재미있었던 일 있었는지 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (193, '최근 가장 많이 하는 생각 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (194, '새로 생긴 취미 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (195, '요즘 자주 가는 장소 공유해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (196, '최근에 했던 도전 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (197, '지금 하고 있는 일 적성에 맞는지 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (198, '요즘 자주 듣는 노래 공유해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (199, '재밌게 본 영화나 드라마 추천해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (200, '자주 보는 유튜브 채널, SNS 채널 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (201, '최근에 발견한 맛집 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (202, '제일 좋아하는 시간대나 요일 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (203, '앞으로 해보고 싶은 일(거) 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (204, '요즘 빠진 앱이나 게임 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (205, '쇼핑할 때 보는 기준 공유해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (206, '최근에 샀던 물건 중 만족했던 거 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (207, '최근에 다녀온 여행지 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (208, '가고 싶은 국내/해외 여행지 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (209, '여행 스타일 공유해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (210, '괜찮은 여행지나 에피소드 나눠보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (211, '꼭 해보고 싶은 버킷리스트 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (212, '혼자 여행 경험 있는지 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (213, '어릴적 추억의 장소 나눠보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (214, '친구들 중 연락 닿은 사람 있는지 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (215, '요즘 가장 많이 하는 생각 이야기해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (216, '스트레스 받을 때 푸는 방법 공유해보기', 'OLD_FRIEND');
INSERT INTO topic VALUES (217, '부모님이 받고 싶은 선물 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (218, '가족여행 계획 해보기', 'FAMILY');
INSERT INTO topic VALUES (219, '태몽 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (220, '부모님 결혼 결심한 이유 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (221, '서로 바라는 점 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (222, '아들, 딸 키우시면서 힘들었던 기억 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (223, '아들, 딸 키우시면서 가장 행복했던 일 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (224, '아들, 딸 키우시면서 다른 집 자식이 부러운 점 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (225, '말을 가장 안들었던 형제 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (226, '말을 가장 잘 들었던 형제 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (227, '미래가 걱정되는 형제 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (228, '알아서 잘해서 신경 안썼던 형제 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (229, '결혼할 수 있을까 걱정되는 형제 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (230, '우리 가족 미래 모습 상상해보기', 'FAMILY');
INSERT INTO topic VALUES (231, '부모님 학생 시절 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (232, '부모님 첫만남 썰 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (233, '가족 모임 정해보기', 'FAMILY');
INSERT INTO topic VALUES (234, '부모님이 바라는 미래 사위, 며느리 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (235, '내자식이지만 결혼 못할 것 같은 형제 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (236, '내자식이지만 밖에서 다소 부끄러운 형제 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (237, '부모님께 감사한 점 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (238, '자식들에게 고마웠던 점 얘기해보기', 'FAMILY');
INSERT INTO topic VALUES (239, '오늘 하루 어떻게 보냈는지에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (240, '요즘 가장 관심 있는 주제에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (241, '최근에 재미있게 본 영화나 드라마에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (242, '좋아하는 음악이나 요즘 자주 듣는 노래에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (243, '주말에 주로 하는 활동에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (244, '가보고 싶은 여행지에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (245, '최근에 읽은 책 중 추천할 만한 책에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (246, '맛집 탐방 경험이나 기억에 남는 맛집에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (247, '좋아하는 음식이나 싫어하는 음식에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (248, '운동이나 스포츠를 좋아하는지에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (249, '취미나 여가 시간에 주로 하는 활동에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (250, 'SNS나 유튜브에서 자주 보는 콘텐츠에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (251, '가장 기억에 남는 여행지에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (252, '특별히 관심 있는 분야나 배우고 싶은 것에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (253, '이전에 살았던 곳이나 자주 가는 곳에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (254, '강아지, 고양이 등 반려동물을 좋아하는지에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (255, '좋아하는 계절과 그 이유에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (256, '어릴 때 좋아했던 만화나 애니메이션에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (257, '최근에 새롭게 도전해본 일에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (258, '게임을 좋아하는지, 요즘 하는 게임에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (259, '카페나 술집 중 자주 가는 곳에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (260, '평소 좋아하는 패션 스타일에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (261, '혼자 있을 때와 사람들과 함께 있을 때 어느 쪽이 더 편한지 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (262, '어떤 유형의 사람과 잘 맞는다고 생각하는지 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (263, '평소 스트레스를 푸는 방법에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (264, '최근에 감동받았던 일이나 기분 좋았던 일에 대해 얘기해보기', 'FIRST_FRIEND');
INSERT INTO topic VALUES (265, '올해 안에 꼭 이루고 싶은 목표에 대해 얘기해보기', 'FIRST_FRIEND');

END;